#!/usr/bin/env python3
"""
CodeGuard AI - AI Pattern Detection System

Machine learning-based system to detect AI-generated code patterns.
Uses multiple detection strategies including statistical analysis, pattern matching,
and ML models to identify code that may have been generated by AI tools.
"""

import hashlib
import json
import logging
import re
from dataclasses import dataclass, asdict
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, Tuple, Set

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

from .ast_parser import ParseResult, ASTNode, LanguageType

# Configure logging
logger = logging.getLogger(__name__)

class AIConfidenceLevel(Enum):
    """Confidence levels for AI detection"""
    VERY_LOW = "very_low"      # 0-20%
    LOW = "low"                # 20-40%
    MEDIUM = "medium"          # 40-60%
    HIGH = "high"              # 60-80%
    VERY_HIGH = "very_high"    # 80-100%

class DetectionMethod(Enum):
    """AI detection methods"""
    STATISTICAL = "statistical"
    PATTERN_MATCHING = "pattern_matching"
    STYLE_ANALYSIS = "style_analysis"
    COMMENT_ANALYSIS = "comment_analysis"
    STRUCTURE_ANALYSIS = "structure_analysis"
    ML_MODEL = "ml_model"

@dataclass
class AIPattern:
    """Detected AI pattern information"""
    pattern_type: str
    confidence: float
    method: DetectionMethod
    description: str
    line_start: int = 0
    line_end: int = 0
    evidence: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.evidence is None:
            self.evidence = {}
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class AIDetectionResult:
    """Result of AI detection analysis"""
    overall_confidence: float
    confidence_level: AIConfidenceLevel
    is_likely_ai_generated: bool
    patterns: List[AIPattern]
    analysis_summary: Dict[str, Any]
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'overall_confidence': self.overall_confidence,
            'confidence_level': self.confidence_level.value,
            'is_likely_ai_generated': self.is_likely_ai_generated,
            'patterns': [p.to_dict() for p in self.patterns],
            'analysis_summary': self.analysis_summary,
            'timestamp': self.timestamp.isoformat()
        }

class StatisticalAnalyzer:
    """Statistical analysis for AI detection"""
    
    def __init__(self):
        self.human_patterns = self._load_human_patterns()
        self.ai_patterns = self._load_ai_patterns()
    
    def _load_human_patterns(self) -> Dict[str, Any]:
        """Load statistical patterns typical of human-written code"""
        return {
            'avg_line_length': {'mean': 45, 'std': 15},
            'function_length': {'mean': 12, 'std': 8},
            'variable_name_entropy': {'mean': 3.2, 'std': 0.8},
            'comment_frequency': {'mean': 0.15, 'std': 0.1},
            'indentation_consistency': {'mean': 0.95, 'std': 0.05}
        }
    
    def _load_ai_patterns(self) -> Dict[str, Any]:
        """Load statistical patterns typical of AI-generated code"""
        return {
            'avg_line_length': {'mean': 52, 'std': 8},
            'function_length': {'mean': 18, 'std': 5},
            'variable_name_entropy': {'mean': 2.8, 'std': 0.6},
            'comment_frequency': {'mean': 0.25, 'std': 0.08},
            'indentation_consistency': {'mean': 0.98, 'std': 0.02}
        }
    
    def analyze(self, code: str, ast_result: ParseResult) -> List[AIPattern]:
        """Perform statistical analysis to detect AI patterns"""
        patterns = []
        
        # Calculate code statistics
        stats = self._calculate_statistics(code, ast_result)
        
        # Compare against known patterns
        for metric, value in stats.items():
            ai_score = self._calculate_likelihood_score(metric, value, self.ai_patterns)
            human_score = self._calculate_likelihood_score(metric, value, self.human_patterns)
            
            if ai_score > human_score and ai_score > 0.6:
                patterns.append(AIPattern(
                    pattern_type=f"statistical_{metric}",
                    confidence=ai_score,
                    method=DetectionMethod.STATISTICAL,
                    description=f"Statistical anomaly in {metric}: {value:.2f}",
                    evidence={'metric': metric, 'value': value, 'ai_score': ai_score}
                ))
        
        return patterns
    
    def _calculate_statistics(self, code: str, ast_result: ParseResult) -> Dict[str, float]:
        """Calculate statistical metrics from code"""
        lines = code.split('\n')
        non_empty_lines = [line for line in lines if line.strip()]
        
        stats = {
            'avg_line_length': np.mean([len(line) for line in non_empty_lines]) if non_empty_lines else 0,
            'line_length_variance': np.var([len(line) for line in non_empty_lines]) if non_empty_lines else 0,
            'comment_frequency': len(re.findall(r'#.*|//.*|/\*[\s\S]*?\*/', code)) / max(len(non_empty_lines), 1),
            'indentation_consistency': self._calculate_indentation_consistency(lines),
            'variable_name_entropy': self._calculate_variable_entropy(code)
        }
        
        if ast_result.metrics:
            stats['function_length'] = ast_result.metrics.lines_of_code / max(ast_result.metrics.function_count, 1)
            stats['cyclomatic_complexity'] = ast_result.metrics.cyclomatic_complexity
        
        return stats
    
    def _calculate_likelihood_score(self, metric: str, value: float, patterns: Dict[str, Any]) -> float:
        """Calculate likelihood score for a metric against known patterns"""
        if metric not in patterns:
            return 0.5
        
        pattern = patterns[metric]
        mean = pattern['mean']
        std = pattern['std']
        
        # Calculate normalized distance from mean
        distance = abs(value - mean) / std
        
        # Convert to probability (closer to mean = higher probability)
        return max(0, 1 - distance / 3)  # 3-sigma rule
    
    def _calculate_indentation_consistency(self, lines: List[str]) -> float:
        """Calculate indentation consistency score"""
        indentations = []
        for line in lines:
            if line.strip():
                indent = len(line) - len(line.lstrip())
                indentations.append(indent)
        
        if not indentations:
            return 1.0
        
        # Check for consistent indentation patterns
        unique_indents = set(indentations)
        if len(unique_indents) <= 3:  # Very consistent
            return 0.95
        elif len(unique_indents) <= 6:  # Moderately consistent
            return 0.8
        else:  # Inconsistent
            return 0.6
    
    def _calculate_variable_entropy(self, code: str) -> float:
        """Calculate entropy of variable names"""
        # Extract variable names using regex
        var_pattern = r'\b[a-zA-Z_][a-zA-Z0-9_]*\b'
        variables = re.findall(var_pattern, code)
        
        if not variables:
            return 0
        
        # Calculate character frequency entropy
        char_freq = {}
        total_chars = 0
        
        for var in variables:
            for char in var.lower():
                char_freq[char] = char_freq.get(char, 0) + 1
                total_chars += 1
        
        if total_chars == 0:
            return 0
        
        # Calculate Shannon entropy
        entropy = 0
        for freq in char_freq.values():
            prob = freq / total_chars
            entropy -= prob * np.log2(prob)
        
        return entropy

class PatternMatcher:
    """Pattern matching for known AI-generated code signatures"""
    
    def __init__(self):
        self.ai_signatures = self._load_ai_signatures()
        self.suspicious_patterns = self._load_suspicious_patterns()
    
    def _load_ai_signatures(self) -> List[Dict[str, Any]]:
        """Load known AI code signatures"""
        return [
            {
                'name': 'copilot_comment_style',
                'pattern': r'# This (function|method|class) (does|performs|handles)',
                'confidence': 0.7,
                'description': 'GitHub Copilot-style comments'
            },
            {
                'name': 'chatgpt_variable_naming',
                'pattern': r'\b(result|output|data|info|temp|val)\d*\b',
                'confidence': 0.6,
                'description': 'Generic variable names common in AI-generated code'
            },
            {
                'name': 'ai_error_handling',
                'pattern': r'except Exception as e:\s*print\(.*e.*\)',
                'confidence': 0.8,
                'description': 'Generic exception handling pattern'
            },
            {
                'name': 'ai_docstring_style',
                'pattern': r'"""\s*This (function|method|class) (is used to|performs|handles)',
                'confidence': 0.75,
                'description': 'AI-generated docstring patterns'
            }
        ]
    
    def _load_suspicious_patterns(self) -> List[Dict[str, Any]]:
        """Load patterns that are suspicious but not definitive"""
        return [
            {
                'name': 'perfect_formatting',
                'pattern': r'^\s*$\n^\s*$\n',  # Multiple consecutive empty lines
                'confidence': 0.4,
                'description': 'Overly perfect formatting'
            },
            {
                'name': 'verbose_comments',
                'pattern': r'#.*\b(obviously|clearly|simply|just|merely)\b',
                'confidence': 0.5,
                'description': 'Verbose explanatory comments'
            }
        ]
    
    def analyze(self, code: str) -> List[AIPattern]:
        """Analyze code for known AI patterns"""
        patterns = []
        
        # Check AI signatures
        for signature in self.ai_signatures:
            matches = list(re.finditer(signature['pattern'], code, re.IGNORECASE | re.MULTILINE))
            
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                patterns.append(AIPattern(
                    pattern_type=signature['name'],
                    confidence=signature['confidence'],
                    method=DetectionMethod.PATTERN_MATCHING,
                    description=signature['description'],
                    line_start=line_num,
                    line_end=line_num,
                    evidence={'match': match.group(), 'pattern': signature['pattern']}
                ))
        
        # Check suspicious patterns
        for pattern_info in self.suspicious_patterns:
            matches = list(re.finditer(pattern_info['pattern'], code, re.IGNORECASE | re.MULTILINE))
            
            for match in matches:
                line_num = code[:match.start()].count('\n') + 1
                patterns.append(AIPattern(
                    pattern_type=pattern_info['name'],
                    confidence=pattern_info['confidence'],
                    method=DetectionMethod.PATTERN_MATCHING,
                    description=pattern_info['description'],
                    line_start=line_num,
                    line_end=line_num,
                    evidence={'match': match.group(), 'pattern': pattern_info['pattern']}
                ))
        
        return patterns

class StyleAnalyzer:
    """Analyze coding style for AI detection"""
    
    def analyze(self, code: str, ast_result: ParseResult) -> List[AIPattern]:
        """Analyze coding style patterns"""
        patterns = []
        
        # Check for overly consistent style
        consistency_score = self._analyze_style_consistency(code)
        if consistency_score > 0.95:
            patterns.append(AIPattern(
                pattern_type="overly_consistent_style",
                confidence=0.6,
                method=DetectionMethod.STYLE_ANALYSIS,
                description="Code style is unusually consistent, possibly AI-generated",
                evidence={'consistency_score': consistency_score}
            ))
        
        # Check for perfect naming conventions
        naming_score = self._analyze_naming_conventions(code)
        if naming_score > 0.9:
            patterns.append(AIPattern(
                pattern_type="perfect_naming_conventions",
                confidence=0.5,
                method=DetectionMethod.STYLE_ANALYSIS,
                description="Naming conventions are unusually perfect",
                evidence={'naming_score': naming_score}
            ))
        
        return patterns
    
    def _analyze_style_consistency(self, code: str) -> float:
        """Analyze style consistency"""
        lines = code.split('\n')
        
        # Check indentation consistency
        indent_sizes = []
        for line in lines:
            if line.strip():
                indent = len(line) - len(line.lstrip())
                if indent > 0:
                    indent_sizes.append(indent)
        
        if not indent_sizes:
            return 1.0
        
        # Calculate consistency (low variance = high consistency)
        variance = np.var(indent_sizes)
        consistency = 1 / (1 + variance)
        
        return min(consistency, 1.0)
    
    def _analyze_naming_conventions(self, code: str) -> float:
        """Analyze naming convention adherence"""
        # Extract function and variable names
        func_pattern = r'def\s+([a-zA-Z_][a-zA-Z0-9_]*)'
        var_pattern = r'\b([a-zA-Z_][a-zA-Z0-9_]*)\s*='
        
        functions = re.findall(func_pattern, code)
        variables = re.findall(var_pattern, code)
        
        all_names = functions + variables
        if not all_names:
            return 0.5
        
        # Check snake_case adherence
        snake_case_count = sum(1 for name in all_names if re.match(r'^[a-z_][a-z0-9_]*$', name))
        
        return snake_case_count / len(all_names)

class AIDetectionEngine:
    """Main AI detection engine that coordinates all detection methods"""
    
    def __init__(self):
        self.statistical_analyzer = StatisticalAnalyzer()
        self.pattern_matcher = PatternMatcher()
        self.style_analyzer = StyleAnalyzer()
        
        # Initialize ML model (placeholder for now)
        self.ml_model = None
        self._initialize_ml_model()
    
    def _initialize_ml_model(self):
        """Initialize machine learning model for AI detection"""
        # Placeholder for ML model initialization
        # In a real implementation, this would load a pre-trained model
        self.ml_model = IsolationForest(contamination=0.1, random_state=42)
    
    def detect_ai_patterns(self, code: str, filename: str = "", ast_result: Optional[ParseResult] = None) -> AIDetectionResult:
        """Detect AI-generated code patterns using multiple methods"""
        try:
            # Parse AST if not provided
            if ast_result is None:
                from .ast_parser import parse_code
                ast_result = parse_code(code, filename)
            
            all_patterns = []
            
            # Statistical analysis
            if ast_result.success:
                statistical_patterns = self.statistical_analyzer.analyze(code, ast_result)
                all_patterns.extend(statistical_patterns)
            
            # Pattern matching
            pattern_matches = self.pattern_matcher.analyze(code)
            all_patterns.extend(pattern_matches)
            
            # Style analysis
            if ast_result.success:
                style_patterns = self.style_analyzer.analyze(code, ast_result)
                all_patterns.extend(style_patterns)
            
            # Calculate overall confidence
            overall_confidence = self._calculate_overall_confidence(all_patterns)
            
            # Determine confidence level
            confidence_level = self._get_confidence_level(overall_confidence)
            
            # Determine if likely AI-generated
            is_likely_ai = overall_confidence > 0.6
            
            # Create analysis summary
            analysis_summary = self._create_analysis_summary(all_patterns, ast_result)
            
            return AIDetectionResult(
                overall_confidence=overall_confidence,
                confidence_level=confidence_level,
                is_likely_ai_generated=is_likely_ai,
                patterns=all_patterns,
                analysis_summary=analysis_summary
            )
            
        except Exception as e:
            logger.error(f"Error in AI detection: {str(e)}")
            return AIDetectionResult(
                overall_confidence=0.0,
                confidence_level=AIConfidenceLevel.VERY_LOW,
                is_likely_ai_generated=False,
                patterns=[],
                analysis_summary={'error': str(e)}
            )
    
    def _calculate_overall_confidence(self, patterns: List[AIPattern]) -> float:
        """Calculate overall confidence from individual patterns"""
        if not patterns:
            return 0.0
        
        # Weight patterns by method reliability
        method_weights = {
            DetectionMethod.STATISTICAL: 0.3,
            DetectionMethod.PATTERN_MATCHING: 0.4,
            DetectionMethod.STYLE_ANALYSIS: 0.2,
            DetectionMethod.ML_MODEL: 0.5
        }
        
        weighted_sum = 0.0
        total_weight = 0.0
        
        for pattern in patterns:
            weight = method_weights.get(pattern.method, 0.1)
            weighted_sum += pattern.confidence * weight
            total_weight += weight
        
        if total_weight == 0:
            return 0.0
        
        return min(weighted_sum / total_weight, 1.0)
    
    def _get_confidence_level(self, confidence: float) -> AIConfidenceLevel:
        """Convert numeric confidence to confidence level"""
        if confidence >= 0.8:
            return AIConfidenceLevel.VERY_HIGH
        elif confidence >= 0.6:
            return AIConfidenceLevel.HIGH
        elif confidence >= 0.4:
            return AIConfidenceLevel.MEDIUM
        elif confidence >= 0.2:
            return AIConfidenceLevel.LOW
        else:
            return AIConfidenceLevel.VERY_LOW
    
    def _create_analysis_summary(self, patterns: List[AIPattern], ast_result: Optional[ParseResult]) -> Dict[str, Any]:
        """Create summary of analysis results"""
        summary = {
            'total_patterns_detected': len(patterns),
            'methods_used': list(set(p.method.value for p in patterns)),
            'pattern_types': list(set(p.pattern_type for p in patterns)),
            'highest_confidence_pattern': max(patterns, key=lambda p: p.confidence).to_dict() if patterns else None
        }
        
        if ast_result and ast_result.success:
            summary['code_metrics'] = ast_result.metrics.to_dict() if ast_result.metrics else None
            summary['language'] = ast_result.language.value
        
        return summary

# Global detector instance
ai_detector = AIDetectionEngine()

# Convenience functions
def detect_ai_code(code: str, filename: str = "") -> AIDetectionResult:
    """Detect AI-generated patterns in code"""
    return ai_detector.detect_ai_patterns(code, filename)

def is_likely_ai_generated(code: str, filename: str = "") -> bool:
    """Check if code is likely AI-generated"""
    result = ai_detector.detect_ai_patterns(code, filename)
    return result.is_likely_ai_generated

def get_ai_confidence(code: str, filename: str = "") -> float:
    """Get AI confidence score for code"""
    result = ai_detector.detect_ai_patterns(code, filename)
    return result.overall_confidence